# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_coin_hive', '0002_auto_20170922_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinHiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('interval', models.FloatField()),
                ('time_live', models.FloatField()),
                ('hashes', models.IntegerField()),
                ('tag', models.CharField(db_index=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_coin_hive.CoinHiveUser')),
            ],
        ),
        migrations.CreateModel(
            name='CoinHiveSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_name', models.CharField(max_length=255)),
                ('site_key', models.CharField(max_length=32)),
                ('secret_key', models.CharField(max_length=32)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coinhivetoken',
            name='hashes',
        ),
        migrations.RemoveField(
            model_name='coinhivetoken',
            name='secret',
        ),
        migrations.AlterField(
            model_name='coinhivetoken',
            name='token',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='coinhivetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_coin_hive.CoinHiveUser'),
        ),
    ]
