# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_coin_hive', '0005_auto_20171007_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhivesite',
            name='secret_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coinhivesite',
            name='site_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coinhiveuser',
            name='name',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Username for coin-hive'),
        ),
    ]
